---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)

source("inst/extdata/current_link_for_shared_script")
```

# Package compagnon du cours "Introduction à R"

<!-- badges: start -->
<!-- badges: end -->

## Supports de cours

|  Date  | Thématique | Lien vers la présentation |
|--------|------------|---------------------------|
| Lundi et Mardi | Cours de YM | [[cours et exercices](inst/extdata/jours1et2.zip)] |
| Mercredi | Programme | [[HTML](vignettes/S00programme.html) [PDF](vignettes/S00programme.pdf)] |
| Mercredi | R & Rstudio  | [[HTML](vignettes/S01rstudio.html) [PDF](vignettes/S01rstudio.pdf)] |
| Mercredi | Packages  | [[HTML](vignettes/S02packages.html) [PDF](vignettes/S02packages.pdf)] |
| Mercredi | Objets     | [[HTML](vignettes/S03objets.html) [PDF](vignettes/S03objets.pdf)] |
| Mercredi | ggplot2   | [[HTML](vignettes/S04ggplot2.html) [PDF](vignettes/S04ggplot2.pdf)] |
| Mercredi | TP  | [[Sujet](inst/extdata/tpjeudi.pdf) [Données](inst/extdata/nutrimenu.zip)]|
| Jeudi | Visualisation  | [[HTML](vignettes/S05visu.html) [PDF](vignettes/S05visu.pdf)] |
| Jeudi | Analyse   |  [[HTML](vignettes/S06tests.html) [PDF](vignettes/S06tests.pdf)] |
| Jeudi | TP | [[Sujet](inst/extdata/tpjeudi.pdf) [Données](inst/extdata/nutrimenu.zip)] |


****

Les essentiels pour le cours : 

  * [Document partagé pour écrire du code ensemble](`r currentlink`)
  * Kahoot : [www.kahoot.it](www.kahoot.it)
  * Les données [fruits et légumes](inst/extdata/fruits_and_veggies.xlsx) et les données de [recettes](inst/extdata/nutrimenu.xlsx) (au format `xlsx`)

****

Des références utiles : 

  * Posit (fka Rstudio) : [https://posit.co](https://posit.co)
  * [Rstudio (desktop)](https://posit.co/download/rstudio-desktop/)
  * Comprehensive R Archive Network : [https://cran.r-project.org/](https://cran.r-project.org/)
  * Bioconductor : [https://www.bioconductor.org/](https://www.bioconductor.org/)
  * L'[aide-mémoire créé par Julien Chiquet](inst/extdata/CommandesUsuelles.pdf)
  * Le livre d'Hadley Wickham [R for Data Science](https://r4ds.hadley.nz/)

****

Les [feuilles de triches de Rstudio](https://rstudio.github.io/cheatsheets/) : 

  * Pour [dplyr au format HTML](https://rstudio.github.io/cheatsheets/html/data-transformation.html) et au [format PDF](https://rstudio.github.io/cheatsheets/data-transformation.pdf)
  * Pour [ggplot2 au format HTML](https://rstudio.github.io/cheatsheets/html/data-visualization.html) et au [format PDF](https://rstudio.github.io/cheatsheets/data-visualization.pdf)
  * Pour [lubridate au format HTML](https://rstudio.github.io/cheatsheets/html/lubridate.html) et au [format PDF](https://rstudio.github.io/cheatsheets/lubridate.pdf)

****

Lien vers les tutoriels au format R Markdown : [Lien vers dossier compressé](inst/extdata/tutorials.zip). Pour générer une version locale du tutoriel, ouvrez le sur Rstudio, installez les packages manquants et cliquez sur "Knit".
